version: "3.4"

services:

  post-service:
    image: docker.io/gtadam89/database:latest
    expose: 
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      internal:
        ipv4_address: 10.5.12.5

networks:

  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.12.0/24