---
- name: Deployment of Docker Compose Service
  hosts: all
  tasks:

    - name: Ensure directory structure exists
      become: true
      file: path=/etc/adamsantiago/database state=directory

    - name: Copy docker compose to appropriate directory
      become: true
      copy:
        src: docker-compose.yml
        dest: /etc/adamsantiago/database/docker-compose.yml
        owner: gadam
        group: gadam
        mode: '0755'

    - name: Copy service to appropriate directory
      become: true
      copy:
        src: database.service
        dest: /etc/systemd/system/database.service
        owner: gadam
        group: gadam
        mode: '0755'

    - name: Reload configurations for service
      become: true
      systemd:
        daemon_reload: yes

    - name: Ensure database service begins on startup
      become: true
      systemd:
        name: database
        enabled: yes
        masked: no

    - name: Make sure database service is running
      become: true
      systemd:
        state: restarted
        name: database